version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "9090:9090"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=9090
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Montar el socket Docker del host
    user: root # Ejecutar como root para evitar problemas de permisos
    restart: always

  evaluacion-devops:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluacion-devops
    ports:
      - "8080:8080"
    depends_on:
      - jenkins # Asegurar que Jenkins se levante antes si hay alguna dependencia
    restart: always

volumes:
  jenkins_home:
