version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins # Usar un Dockerfile personalizado para Jenkins
    container_name: jenkins
    ports:
      - "9090:9090"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  evaluacion-devops:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always

volumes:
  jenkins_home:
